export const accessibilityMatrix=[
['HomeV3','home','Primary CTA labelled','Yes','Dynamic type title wraps','Yes'],
['InspectV3','inspect','Scan + upload are named','Yes','Setup cards wrap','Yes'],
['VINV3','vin','Scanner has capture label','Yes','VIN uses mono','Yes'],
['MarketV3','market','Price chart has text summary','Yes','Comparable cards stack','Yes'],
['CameraV3','camera','Capture control 52pt+','Yes','Guidance text visible','Yes'],
['EvidenceV3','evidence','Media tiles have labels','Yes','Annotations not color-only','Yes'],
['AIV3','ai','AI result is labelled','Yes','Risk score has text','Yes'],
['ChecklistV3','checklist','Rows expose status + title','Yes','Tabs can scroll','Yes'],
['TestDriveV3','test','Controls have labels','Yes','Gauge values are textual','Yes'],
['CostsV3','costs','Ranges are text','Yes','Charts have labels','Yes'],
['NegotiationV3','negotiation','Copy action labelled','Yes','Script wraps','Yes'],
['ReportV3','report','Sections have headings','Yes','Images have contextual labels','Yes'],
['DocumentsV3','documents','Documents announce status','Yes','Rows remain readable','Yes'],
['CertificateV3','certificate','Verification fields readable','Yes','Hash uses mono','Yes'],
['ContractV3','contract','Review CTA named','Yes','Document preview scrollable','Yes'],
['SignatureV3','signature','Signing CTA explicit','Yes','Disclosure readable','Yes'],
['HistoryV3','history','Cards identify vehicle','Yes','Filters scroll','Yes'],
['CompareV3','compare','Columns have context','Yes','Rows wrap safely','Yes'],
['ProfileV3','profile','Rows have labels','Yes','Plan badge text-based','Yes'],
['SettingsV3','settings','Setting rows labelled','Yes','Large type supported','Yes'],
['PaywallV3','paywall','CTA and price named','Yes','Feature list wraps','Yes'],
['CopilotV3','copilot','Composer labelled','Yes','Messages wrap','Yes'],
['NotificationsV3','notifications','Unread state textual','Yes','Long messages wrap','Yes'],
['ShareV3','share','Share choices named','Yes','Privacy copy visible','Yes'],
['MaintenanceV3','maintenance','Reminder action named','Yes','Timelines wrap','Yes'],
['MarketplaceV3','marketplace','Comparable cards labelled','Yes','Images have context','Yes'],
['VehicleDetailV3','detail','Vehicle identity explicit','Yes','Specs wrap','Yes'],
['DemoV3','demo','Journey actions named','Yes','Steps scroll','Yes'],
['PresentationV3','presentation','Showcase can be navigated','Yes','Headlines wrap','Yes'],
['QAVisualV3','qa','QA labels semantic','Yes','State rows readable','Yes'],
];
export const qaRules=[
'No essential meaning may depend only on color.',
'Every media tile needs an accessible name.',
'Every async request needs loading, success and recovery states.',
'Every permission denial needs a recovery path.',
'Every AI result needs explicit estimate/uncertainty language where appropriate.',
'Every high-impact CTA needs a minimum 44pt touch target.',
'Every screen must remain usable at larger text sizes.',
'Reduced motion must remove decorative looping motion while preserving state change.',
'Images should have useful fallbacks when network media fails.',
'Sensitive sharing controls must be explicit before the share action.',
];
