export const scenarios={
home:{route:'home',title:'Garage',states:['idle','empty','offline'],data:{activeInspection:true,progress:.72}},
inspect:{route:'inspect',title:'New inspection',states:['idle','permission','error'],data:{step:1}},
vin:{route:'vin',title:'VIN scanner',states:['idle','loading','success','permission','error'],data:{confidence:.98}},
market:{route:'market',title:'Market intelligence',states:['idle','loading','error','offline'],data:{asking:21900,market:21100}},
camera:{route:'camera',title:'Capture evidence',states:['idle','permission','error'],data:{completed:4,total:8}},
evidence:{route:'evidence',title:'Evidence review',states:['idle','empty','error'],data:{photos:18,videos:2,documents:3}},
ai:{route:'ai',title:'AI analysis',states:['loading','review','complete','error'],data:{risk:68,findings:4}},
checklist:{route:'checklist',title:'Inspection checklist',states:['idle','loading','offline','complete'],data:{checked:17,total:24}},
test:{route:'test',title:'Test drive',states:['idle','active','complete'],data:{score:8.2}},
costs:{route:'costs',title:'Repair costs',states:['idle','loading','error'],data:{low:980,high:2570}},
negotiation:{route:'negotiation',title:'Negotiation coach',states:['idle','review'],data:{target:19400,max:20000}},
report:{route:'report',title:'Inspection report',states:['idle','loading','empty','error','complete'],data:{risk:68}},
documents:{route:'documents',title:'Document center',states:['idle','empty','processing','error'],data:{count:3}},
certificate:{route:'certificate',title:'Verified certificate',states:['idle','processing','complete'],data:{verified:true}},
contract:{route:'contract',title:'Purchase contract',states:['draft','review','complete'],data:{price:19400}},
signature:{route:'signature',title:'Human signature',states:['review','signing','complete','error'],data:{human:true}},
history:{route:'history',title:'Inspection history',states:['idle','empty','loading'],data:{vehicles:12}},
compare:{route:'compare',title:'Compare vehicles',states:['idle','empty'],data:{selected:2}},
profile:{route:'profile',title:'Profile',states:['idle'],data:{plan:'Pro'}},
settings:{route:'settings',title:'Settings',states:['idle'],data:{dark:true}},
paywall:{route:'paywall',title:'CarWise Pro',states:['idle','restore','error'],data:{monthly:9.99,yearly:99.99}},
copilot:{route:'copilot',title:'Ask CarWise',states:['idle','thinking','reply','error'],data:{context:'2020 Honda Accord Sport'}},
notifications:{route:'notifications',title:'Notifications',states:['idle','empty'],data:{unread:4}},
share:{route:'share',title:'Share report',states:['preview','success','error'],data:{publicSafe:true}},
maintenance:{route:'maintenance',title:'Maintenance',states:['idle'],data:{open:3}},
marketplace:{route:'marketplace',title:'Market explorer',states:['idle','loading','empty','error'],data:{count:3}},
detail:{route:'detail',title:'Vehicle detail',states:['idle'],data:{vehicle:'demo-accord'}},
};
export const stateFixtures={
loading:{message:'Working on your inspection…',progress:.64},
empty:{title:'Nothing here yet',message:'Complete your first inspection to populate this area.'},
error:{title:'We could not complete that request',message:'Your saved inspection data is still available.',action:'Retry'},
offline:{title:'Offline mode',message:'Changes are saved locally and will sync later.'},
permission:{title:'Permission needed',message:'Allow access to continue this capture step.'},
review:{title:'Review required',message:'Check the evidence before completing this step.'},
complete:{title:'Complete',message:'This step is finished and linked to your inspection.'},
};
export const sampleQuestions=['Is this asking price reasonable?','What should I inspect next?','Explain the biggest risk.','What should I ask the seller?'];
export const sampleEvidence=[
{id:'ev1',type:'photo',label:'Front bumper',meta:'Scratch',confidence:.92},
{id:'ev2',type:'photo',label:'Passenger rear',meta:'Paint variance',confidence:.81},
{id:'ev3',type:'video',label:'Engine clip',meta:'00:10',confidence:.66},
{id:'ev4',type:'voice',label:'Steering note',meta:'00:08',confidence:.94},
{id:'ev5',type:'document',label:'Service invoice',meta:'PDF',confidence:.93},
];
