import {Animated,Easing} from 'react-native';
import {MOTION} from './tokens';
export const timing=(value,toValue,duration=MOTION.normal)=>Animated.timing(value,{toValue,duration,easing:Easing.out(Easing.cubic),useNativeDriver:true});
export const fadeIn=(opacity,duration=MOTION.normal)=>timing(opacity,1,duration);
export const fadeOut=(opacity,duration=MOTION.fast)=>timing(opacity,0,duration);
export const slideIn=(translateY,from=14,duration=MOTION.normal)=>{translateY.setValue(from);return timing(translateY,0,duration)};
export const scaleIn=(scale,from=.94,duration=MOTION.normal)=>{scale.setValue(from);return timing(scale,1,duration)};
export const springTo=(value,toValue=1)=>Animated.spring(value,{toValue,useNativeDriver:true,...MOTION.spring});
export const pressSequence=(scaleValue)=>({in:()=>springTo(scaleValue,.975),out:()=>springTo(scaleValue,1)});
export const pulse=(value,min=.82,max=1,duration=900)=>Animated.loop(Animated.sequence([Animated.timing(value,{toValue:max,duration,useNativeDriver:true}),Animated.timing(value,{toValue:min,duration,useNativeDriver:true})]));
export const shimmer=(value,duration=650)=>Animated.loop(Animated.sequence([Animated.timing(value,{toValue:1,duration,useNativeDriver:true}),Animated.timing(value,{toValue:.45,duration,useNativeDriver:true})]));
export const countUp=(value,toValue,duration=520)=>Animated.timing(value,{toValue,duration,easing:Easing.out(Easing.cubic),useNativeDriver:false});
export const progress=(value,toValue,duration=420)=>Animated.timing(value,{toValue,duration,easing:Easing.out(Easing.quad),useNativeDriver:false});
export const stagger=(animations,delay=60)=>Animated.stagger(delay,animations);
export const parallel=(animations)=>Animated.parallel(animations);
export const sequence=(animations)=>Animated.sequence(animations);
export const createFadeSlide=(opacity,translateY,reduced=false,delay=0)=>{if(reduced){opacity.setValue(1);translateY.setValue(0);return null}return Animated.sequence([Animated.delay(delay),Animated.parallel([fadeIn(opacity),slideIn(translateY)])])};
export const createPressScale=(scale,reduced=false)=>reduced?{transform:[{scale:1}]}:{transform:[{scale}]};
export const native={fadeIn,fadeOut,slideIn,scaleIn,springTo,pulse,shimmer,countUp,progress,stagger,parallel,sequence};
