/**
 * Deterministic AI failure and recovery states for visual QA only.
 * Each state preserves the inspection and gives the user a useful next action.
 */
export const AI_FAILURE_STATES = [
  {
    id: 'ai-failure-camera-permission',
    operation: 'capture',
    title: 'Camera access is unavailable',
    message: 'CarWise could not open the camera. Your inspection is still saved.',
    detail: 'Choose an existing photo or enable Camera access in Settings.',
    tone: 'permission',
    recoverable: true,
    primaryAction: 'Choose a photo',
    secondaryAction: 'Try camera again',
    preservesEvidence: true,
    retryable: true,
    motion: 'error-recoverable',
  },
  {
    id: 'ai-failure-low-quality',
    operation: 'vision',
    title: 'The image needs another look',
    message: 'Glare and distance make this result too uncertain to summarize.',
    detail: 'Move closer, reduce reflections, and capture the full panel again.',
    tone: 'quality',
    recoverable: true,
    primaryAction: 'Capture again',
    secondaryAction: 'Keep evidence',
    preservesEvidence: true,
    retryable: true,
    motion: 'retry-focus',
  },
  {
    id: 'ai-failure-partial-analysis',
    operation: 'analysis',
    title: 'Analysis paused after partial review',
    message: 'Some evidence was reviewed, but the cross-modal summary is not ready.',
    detail: 'The reviewed evidence remains available. Resume when the connection is stable.',
    tone: 'partial',
    recoverable: true,
    primaryAction: 'Resume analysis',
    secondaryAction: 'Review evidence',
    preservesEvidence: true,
    retryable: true,
    completedStages: ['ingest', 'vision'],
    pendingStages: ['crossModal', 'market', 'explain'],
    motion: 'resume-progress',
  },
  {
    id: 'ai-failure-timeout',
    operation: 'analysis',
    title: 'The analysis timed out',
    message: 'Your photos and notes are safe. The AI service did not finish in time.',
    detail: 'Retry now or continue the inspection without losing your current progress.',
    tone: 'network',
    recoverable: true,
    primaryAction: 'Retry analysis',
    secondaryAction: 'Continue inspection',
    preservesEvidence: true,
    retryable: true,
    retryAfterMs: 0,
    motion: 'retry-pulse',
  },
  {
    id: 'ai-failure-offline',
    operation: 'analysis',
    title: 'You are offline',
    message: 'The current inspection is readable and saved locally.',
    detail: 'AI analysis will resume when a connection is available. Do not restart the inspection.',
    tone: 'offline',
    recoverable: true,
    primaryAction: 'Review saved evidence',
    secondaryAction: 'Retry when online',
    preservesEvidence: true,
    retryable: true,
    queued: true,
    motion: 'offline-crossfade',
  },
  {
    id: 'ai-failure-rate-limit',
    operation: 'analysis',
    title: 'Analysis is temporarily busy',
    message: 'The service is handling more requests than usual.',
    detail: 'Your request can be retried without uploading the evidence again.',
    tone: 'service',
    recoverable: true,
    primaryAction: 'Retry in a moment',
    secondaryAction: 'Review checklist',
    preservesEvidence: true,
    retryable: true,
    retryAfterMs: 15000,
    motion: 'deferred-retry',
  },
  {
    id: 'ai-failure-no-signal',
    operation: 'analysis',
    title: 'No reliable visual signal found',
    message: 'The available evidence does not support a confident finding.',
    detail: 'This is not a diagnosis. Add a clearer image or ask a qualified mechanic to confirm.',
    tone: 'uncertain',
    recoverable: true,
    primaryAction: 'Add better evidence',
    secondaryAction: 'Mark for human review',
    preservesEvidence: true,
    retryable: false,
    confidence: null,
    motion: 'uncertainty-fade',
  },
  {
    id: 'ai-failure-document-parse',
    operation: 'document',
    title: 'Document fields need review',
    message: 'Some text could not be read confidently from this document.',
    detail: 'Keep the original document attached and verify the highlighted fields manually.',
    tone: 'document',
    recoverable: true,
    primaryAction: 'Review fields',
    secondaryAction: 'Upload a clearer copy',
    preservesEvidence: true,
    retryable: true,
    flaggedFields: ['VIN', 'registration expiry'],
    motion: 'field-highlight',
  },
];

export const AI_FAILURE_BY_ID = Object.fromEntries(AI_FAILURE_STATES.map((state) => [state.id, state]));

export const getAiFailureState = (id) => AI_FAILURE_BY_ID[id] || AI_FAILURE_STATES[0];

export const getRecoverableAiFailures = () => AI_FAILURE_STATES.filter((state) => state.recoverable && state.retryable);
