/**
 * CarWise AI Mock Data V5
 * Purpose: rich, deterministic fixtures for frontend visual development.
 * Replace these fixtures with production API/state selectors during integration.
 */
export { exteriorFixtures } from './vision/exteriorFixtures';
export { interiorFixtures } from './vision/interiorFixtures';
export { engineFixtures } from './vision/engineFixtures';
export { wheelsFixtures } from './vision/wheelsFixtures';
export { paintFixtures } from './vision/paintFixtures';
export { glassFixtures } from './vision/glassFixtures';
export { lightsFixtures } from './vision/lightsFixtures';
export { undercarriageFixtures } from './vision/undercarriageFixtures';
export { questionsFixtures } from './copilot/questionsFixtures';
export { answersFixtures } from './copilot/answersFixtures';
export { followupsFixtures } from './copilot/followupsFixtures';
export { seller_promptsFixtures } from './copilot/seller_promptsFixtures';
export { inspection_promptsFixtures } from './copilot/inspection_promptsFixtures';
export { price_promptsFixtures } from './copilot/price_promptsFixtures';
export { safety_promptsFixtures } from './copilot/safety_promptsFixtures';
export { summariesFixtures } from './copilot/summariesFixtures';
export { photo_setsFixtures } from './evidence/photo_setsFixtures';
export { video_clipsFixtures } from './evidence/video_clipsFixtures';
export { voice_notesFixtures } from './evidence/voice_notesFixtures';
export { documentsFixtures } from './evidence/documentsFixtures';
export { timelinesFixtures } from './evidence/timelinesFixtures';
export { annotationsFixtures } from './evidence/annotationsFixtures';
export { quality_statesFixtures } from './evidence/quality_statesFixtures';
export { capture_guidesFixtures } from './evidence/capture_guidesFixtures';
export { price_bandsFixtures } from './market/price_bandsFixtures';
export { comparablesFixtures } from './market/comparablesFixtures';
export { trendsFixtures } from './market/trendsFixtures';
export { geo_marketsFixtures } from './market/geo_marketsFixtures';
export { mileage_curvesFixtures } from './market/mileage_curvesFixtures';
export { deal_signalsFixtures } from './market/deal_signalsFixtures';
export { valuation_explanationsFixtures } from './market/valuation_explanationsFixtures';
export { listing_cardsFixtures } from './market/listing_cardsFixtures';
export { repair_itemsFixtures } from './repair/repair_itemsFixtures';
export { labor_rangesFixtures } from './repair/labor_rangesFixtures';
export { parts_rangesFixtures } from './repair/parts_rangesFixtures';
export { severity_impactsFixtures } from './repair/severity_impactsFixtures';
export { maintenance_forecastsFixtures } from './repair/maintenance_forecastsFixtures';
export { repair_scenariosFixtures } from './repair/repair_scenariosFixtures';
export { cost_waterfallsFixtures } from './repair/cost_waterfallsFixtures';
export { repair_explanationsFixtures } from './repair/repair_explanationsFixtures';
export { checklist_statesFixtures } from './inspection/checklist_statesFixtures';
export { test_driveFixtures } from './inspection/test_driveFixtures';
export { fluidsFixtures } from './inspection/fluidsFixtures';
export { tiresFixtures } from './inspection/tiresFixtures';
export { brakesFixtures } from './inspection/brakesFixtures';
export { electricalFixtures } from './inspection/electricalFixtures';
export { safetyFixtures } from './inspection/safetyFixtures';
export { service_historyFixtures } from './inspection/service_historyFixtures';
export { confidenceFixtures } from './trust/confidenceFixtures';
export { uncertaintyFixtures } from './trust/uncertaintyFixtures';
export { human_reviewFixtures } from './trust/human_reviewFixtures';
export { audit_eventsFixtures } from './trust/audit_eventsFixtures';
export { verificationFixtures } from './trust/verificationFixtures';
export { provenanceFixtures } from './trust/provenanceFixtures';
export { ai_labelsFixtures } from './trust/ai_labelsFixtures';
export { disclaimersFixtures } from './trust/disclaimersFixtures';
export { scan_sequencesFixtures } from './motion/scan_sequencesFixtures';
export { analysis_sequencesFixtures } from './motion/analysis_sequencesFixtures';
export { score_animationsFixtures } from './motion/score_animationsFixtures';
export { chart_animationsFixtures } from './motion/chart_animationsFixtures';
export { sheet_animationsFixtures } from './motion/sheet_animationsFixtures';
export { capture_motionFixtures } from './motion/capture_motionFixtures';
export { success_motionFixtures } from './motion/success_motionFixtures';
export { error_motionFixtures } from './motion/error_motionFixtures';
export { journeysFixtures } from './demo/journeysFixtures';
export { vehiclesFixtures } from './demo/vehiclesFixtures';
export { personasFixtures } from './demo/personasFixtures';
export { edge_casesFixtures } from './demo/edge_casesFixtures';
export { offline_modesFixtures } from './demo/offline_modesFixtures';
export { permissionsFixtures } from './demo/permissionsFixtures';
export { AI_FAILURE_STATES, AI_FAILURE_BY_ID, getAiFailureState, getRecoverableAiFailures } from './demo/aiFailureFixtures';
export { subscriptionsFixtures } from './demo/subscriptionsFixtures';
export { showcase_cardsFixtures } from './demo/showcase_cardsFixtures';
export { AI_FEATURE_UNIVERSE_V5, AI_FEATURE_COUNTS_V5 } from './data/aiFeatureUniverseV5';
export { getV5MockBundle, simulateAiRun, V5_SCENARIO_PRESETS } from './services/mockAiScenarioEngineV5';
export { AI_MOTION_MATRIX_V5, V5_INTERACTION_RECIPES } from './animation/aiMotionMatrixV5';
export { AI_PHOTO_DETECTIONS, AI_CONDITION_NARRATIVES, AI_NEGOTIATION_SCRIPTS, AI_MAINTENANCE_PREDICTIONS, AI_RISK_EXPLANATIONS, AI_CHAT_SCENARIOS, AI_MARKET_INSIGHTS, AI_BUYER_GUIDES, getAiMockBundle } from './data/aiMockData';
export { IOS_MOTION_QA_CASES, IOS_MOTION_RULES, getIosMotionCases } from './motion/iosMotionQaFixtures';
export { default as AIShowcaseV5 } from './showcase/AIShowcaseV5';
