export const DEMO_ANIMATION_TIMELINES={
 home:[
  {at:0,action:'heroFadeIn',duration:260},
  {at:120,action:'progressRingDraw',duration:720},
  {at:360,action:'quickActionsStagger',duration:520},
  {at:690,action:'recentVehicleCarouselReveal',duration:360},
 ],
 vin:[
  {at:0,action:'cameraFrameAppear',duration:220},
  {at:220,action:'scanLineLoop',duration:1400,loop:true},
  {at:1000,action:'vinCharactersResolve',duration:480},
  {at:1600,action:'verificationSeal',duration:680},
 ],
 market:[
  {at:0,action:'vehicleImageParallax',duration:520},
  {at:180,action:'priceCountUp',duration:900},
  {at:420,action:'priceBandDraw',duration:780},
  {at:760,action:'comparablesStagger',duration:620},
  {at:1120,action:'trendLineDraw',duration:740},
 ],
 ai:[
  {at:0,action:'evidenceOrbit',duration:1200,loop:true},
  {at:260,action:'pipelineStep1',duration:500},
  {at:720,action:'pipelineStep2',duration:620},
  {at:1250,action:'pipelineStep3',duration:520},
  {at:1760,action:'riskCountUp',duration:920},
  {at:2200,action:'findingCardsStagger',duration:720},
 ],
 capture:[
  {at:0,action:'targetBreathe',duration:1200,loop:true},
  {at:0,action:'scanLine',duration:1400,loop:true},
  {at:900,action:'qualityPulse',duration:420},
  {at:1400,action:'thumbnailAttach',duration:260},
 ],
 report:[
  {at:0,action:'headerReveal',duration:240},
  {at:180,action:'scoreRingDraw',duration:920},
  {at:480,action:'summaryCardStagger',duration:640},
  {at:900,action:'evidenceMosaicReveal',duration:720},
  {at:1350,action:'timelineDraw',duration:860},
 ],
 certificate:[
  {at:0,action:'shieldGlow',duration:1200,loop:true},
  {at:260,action:'sealDraw',duration:720},
  {at:720,action:'certificateFactsStagger',duration:560},
  {at:1200,action:'shareActionsReveal',duration:360},
 ],
};

export const DEMO_EVENTS=[
 {id:'ev01',type:'screen-enter',screen:'Home',label:'Home screen entered',at:0},
 {id:'ev02',type:'hero-load',screen:'Home',label:'Vehicle hero image loaded',at:120},
 {id:'ev03',type:'progress',screen:'Home',label:'Inspection progress animated',at:360},
 {id:'ev04',type:'tap',screen:'Home',label:'Start Inspection pressed',at:980},
 {id:'ev05',type:'scan-start',screen:'VIN',label:'VIN camera opened',at:1200},
 {id:'ev06',type:'scan-result',screen:'VIN',label:'VIN detected',at:3200},
 {id:'ev07',type:'market-load',screen:'Market',label:'Market comparison loaded',at:3900},
 {id:'ev08',type:'camera-open',screen:'Capture',label:'Exterior capture opened',at:6400},
 {id:'ev09',type:'photo-added',screen:'Capture',label:'Front bumper photo added',at:7800},
 {id:'ev10',type:'video-added',screen:'Capture',label:'Engine video added',at:10600},
 {id:'ev11',type:'voice-added',screen:'Capture',label:'Voice note added',at:12200},
 {id:'ev12',type:'ai-start',screen:'AI Analysis',label:'AI analysis started',at:13400},
 {id:'ev13',type:'ai-finding',screen:'AI Analysis',label:'Warning indicator detected',at:16100},
 {id:'ev14',type:'ai-complete',screen:'AI Analysis',label:'AI analysis complete',at:18100},
 {id:'ev15',type:'report-open',screen:'Report',label:'Report opened',at:19400},
 {id:'ev16',type:'offer-open',screen:'Negotiation',label:'Offer builder opened',at:22100},
 {id:'ev17',type:'contract-open',screen:'Contract',label:'Contract preview opened',at:24700},
 {id:'ev18',type:'signature-review',screen:'Signature',label:'Human review confirmation opened',at:26800},
 {id:'ev19',type:'certificate',screen:'Certificate',label:'Certificate generated',at:29200},
];
